dent: Set $USER and $LOGNAME in container
Since we are trying to emulate a user environment, we must have the
$LOGNAME (required by POSIX) and $USER (not required by POSIX, but
extremely common) variables set. These are normally set by login(1),
but since we don't run that to enter the container, we must set them
ourselves.

`Test` has been updated to confirm that these variables are set. Note
that it explicitly does not use the `-l argument to bash because these
variables should be available even when the user's runnning a one-off
command like `dent deb11 ls`.

This also avoids false negatives (i.e., incorrectly passing) from
systems like Fedora that have an /etc/profile that sets and exports
LOGNAME and USER. (Debian and Ubuntu do not do this, which is how
we discovered the problem.)

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -157,6 +157,18 @@ build_tests() {
         bin/dent $force_rebuild -B $baseimage -t $tag $container true \
             || adderror $baseimage
 
+        #   Confirm that we're ensuring $USER and $LOGNAME are set (even
+        #   for non-login shells: no `-l` here!) because this is supposed
+        #   to be emulating a user environment, even though login(1) or
+        #   similar is not being run.
+        dent $container  bash -c 'echo USER=$USER LOGNAME=$LOGNAME' \
+            | grep "USER=$USER LOGNAME=$LOGNAME" \
+            || {
+                retcode=$(($retcode+1))
+                echo 'ERROR: $USER/$LOGNAME not set?'
+                dent 1>&2 $container  bash -c 'echo USER=$USER LOGNAME=$LOGNAME'
+        }
+
         echo -n "docker container rm -f $container: "
         $docker container rm -f "$container" || true
         $keep_images || {
