dent: Continue on if apt-get update fails
If we've got no network connection, or update servers aren't available
because the system is old, we still try to carry on anyway in case our
image has sufficient information to do so.

This does not fix any current problems, but seems like a good idea.

diff --git a/dent/dent b/dent/dent
--- a/dent/dent
+++ b/dent/dent
@@ -79,7 +79,10 @@ UNIVERSAL_PKGS='sudo curl wget git vim man-db'
 packages_apt() {
     echo '-- Package updates/installs'
     export DEBIAN_FRONTEND=noninteractive
-    apt-get update
+    #   If we fail to download some updates, e.g. due to no network
+    #   connection or updates no longer being available for old systems,
+    #   we'll live with that.
+    apt-get update || true
     #   We must install git and set user.name/email before installing
     #   etckeeper or etckeeper will be unable to commit.
     apt-get -y install git
